const courses = [
  {
    id: 'graphql',
    title: 'GraphQL: Introduction to GraphQL for Beginners',
    duration: '2h 40m',
    level: 'Advance',
    rating: 2.5,
    reviews: 1500,
    price: '$500',
    originalPrice: '$600',
    image: 'assets/course-graphql.jpg',
    instructor: {
      name: 'Brooblyn Simmons',
      avatar: 'assets/avatar-5.jpg',
    },
  },
  {
    id: 'javascript',
    title: "A Complete Beginner's Guide to JavaScript",
    duration: '4h 10m',
    level: 'Advance',
    rating: 3.5,
    reviews: 7500,
    price: '$700',
    discountPrice: '$850',
    image: 'assets/course-javascript.jpg',
    instructor: {
      name: 'Jenny Wilson',
      avatar: 'assets/avatar-1.jpg',
    },
  },
  {
    id: 'nodejs',
    title: 'Beginning Node.js, Express & MongoDB Development',
    duration: '2h 00m',
    level: 'Intermediate',
    rating: 4.0,
    reviews: 15700,
    price: '$800',
    discountPrice: '$950',
    image: 'assets/course-node.jpg',
    instructor: {
      name: 'Sina Ray',
      avatar: 'assets/avatar-3.jpg',
    },
  },
  {
    id: 'react',
    title: 'How to Easily Create a Website with React',
    duration: '3h 55m',
    level: 'Advance',
    rating: 4.5,
    reviews: 1500,
    price: '$600',
    discountPrice: '$750',
    image: 'assets/course-react.jpg',
    instructor: {
      name: 'April Noms',
      avatar: 'assets/avatar-2.jpg',
    },
  },
  {
    id: 'html',
    title: 'HTML Full Course: Build a Website Tutorial',
    duration: '3h 16m',
    level: 'Beginner',
    rating: 3.0,
    reviews: 1600,
    price: '$550',
    discountPrice: '$700',
    image: 'assets/course-html.jpg',
    instructor: {
      name: 'Miston Wilson',
      avatar: 'assets/avatar-8.jpg',
    },
  },
];

export default courses;
